

version: "3"

services: 
  funk-server: # the funk-server to collect all log information and write them to the elasticsearchdb 
    networks: 
      - elk
    ports: 
      - 3000:3000
    image: fasibio/funk_server:latest
    environment: 
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: MagicWord
      ELASTICSEARCH_URL: http://elasticsearch:9200
      CONNECTION_KEY: changeMe7894561323 # Shared Key you have to set on each agent...
      USE_ILM_POLICY: "false"
    labels: 
      "funk.log": "false" #do not log this container! IMPORTANT no ending loop!!! 

  # funk-agent: # the funk agent to collect the logs
  #   networks: 
  #     - elk
  #   image: fasibio/funk_agent:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # Its nesssari to talk with docker it self. Agent will not be running without this
  #   environment:
  #     FUNK_SERVER: ws://funk-server:3000 # the adress to the funk-server it can be external too (is a websocket so ws instance of http and wss instance of https)
  #     CONNECTION_KEY: changeMe7894561323 # The Shared Key configured at your funk-server installation
  #     ENABLE_GEO_IP_INJECT: "true" # Allow this agent to inject geo ip information and the label key funk.log.geodatafromip	 is now enabled see at testhttpd service
  #   labels: 
  #     "funk.searchindex": "funk_agent" # The index at your elasticseach db to collect logs from this container

  kibana: #Your Kibanasystem
    networks: 
      - elk
    ports:
      - 5601:5601
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: MagicWord
      ELASTICSEARCH_URL: http://elasticsearch:9200
    labels: 
      "funk.log.staticcontent": "{\"usage\": \"loganalyze\"}" # Static information to log application cases for example staging
      "funk.searchindex": "kibana" # The index at your elasticseach db to collect logs from this container
      
  elasticsearch:  #Your Elasticsearchdb
    image: elasticsearch:7.2.0
    ports: 
      - 127.0.0.1:9200:9200
      - 9300:9300
    networks: 
      - elk
    environment: 
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: MagicWord
      xpack.security.enabled: "true"
      xpack.ml.enabled: "true"
      xpack.watcher.enabled: "true"
      discovery.type: "single-node"
    labels: 
      "funk.log": "false" #do not log this container
    volumes:
      - esdata01:/usr/share/elasticsearch/data
volumes:
  esdata01: 
    driver: local

networks:
  elk:
    external: true